spring.application.name=core
spring.threads.virtual.enabled=true
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/geomaster}
spring.datasource.username=${DATABASE_USER:geomaster}
spring.datasource.password=${DATABASE_PASSWORD:geomaster}
management.endpoints.web.exposure.include=health,info
springdoc.api-docs.path=/v3/api-docs
